"""initial schema

Revision ID: af352aece3bc
Revises: 
Create Date: 2026-08-10 22:48:07.066346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af352aece3bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('background_jobs',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('queued', 'submitted', 'generating', 'processing', 'downloading', 'uploading', 'running', 'waiting_approval', 'scheduled', 'completed', 'failed', 'retrying', 'cancelled', name='background_job_status', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_lease_expires_at'), 'background_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_locked_by'), 'background_jobs', ['locked_by'], unique=False)
    op.create_index(op.f('ix_background_jobs_organization_id'), 'background_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_table('clients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('products_services', sa.Text(), nullable=True),
    sa.Column('marketing_goals', sa.Text(), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('primary_channels', sa.JSON(), nullable=False),
    sa.Column('kpis', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='client_status', native_enum=False), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_business_name'), 'clients', ['business_name'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='member_role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('ad_accounts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_status', sa.Enum('connected', 'not_connected', 'demo_data', 'sync_error', name='ad_connection_status', native_enum=False), nullable=False),
    sa.Column('encrypted_credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_accounts_client_id'), 'ad_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_ad_accounts_organization_id'), 'ad_accounts', ['organization_id'], unique=False)
    op.create_table('ai_actions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('create_campaign', 'create_ad_set', 'create_ad', 'update_campaign', 'update_budget', 'pause_campaign', 'resume_campaign', 'create_creative', 'generate_image', 'generate_video', 'create_content', 'schedule_content', 'publish_content', 'update_content', 'generate_report', 'generate_recommendation', 'create_lead_action', 'send_notification', 'optimize_campaign', 'generate_creative_variations', name='ai_action_type', native_enum=False), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='ai_action_risk', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='ai_action_priority', native_enum=False), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'executing', 'completed', 'failed', 'cancelled', 'scheduled', name='ai_action_status', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_actions_action_type'), 'ai_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_ai_actions_client_id'), 'ai_actions', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_organization_id'), 'ai_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_platform'), 'ai_actions', ['platform'], unique=False)
    op.create_index(op.f('ix_ai_actions_status'), 'ai_actions', ['status'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_client_id'), 'ai_conversations', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_organization_id'), 'ai_conversations', ['organization_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='recommendation_priority', native_enum=False), nullable=False),
    sa.Column('expected_impact', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'saved', 'completed', name='recommendation_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_client_id'), 'ai_recommendations', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_organization_id'), 'ai_recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_status'), 'ai_recommendations', ['status'], unique=False)
    op.create_table('analytics_daily',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('leads', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.Enum('demo', 'live', name='analytics_daily_source', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_daily_client_id'), 'analytics_daily', ['client_id'], unique=False)
    op.create_index(op.f('ix_analytics_daily_date'), 'analytics_daily', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_daily_organization_id'), 'analytics_daily', ['organization_id'], unique=False)
    op.create_table('autonomy_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('autonomy_mode', sa.Enum('copilot', 'assisted', 'autonomous', name='autonomy_mode', native_enum=False), nullable=False),
    sa.Column('maximum_daily_ad_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_campaign_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_budget_increase_percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('maximum_budget_decrease_percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('maximum_campaigns_per_day', sa.Integer(), nullable=False),
    sa.Column('maximum_creatives_per_day', sa.Integer(), nullable=False),
    sa.Column('maximum_posts_per_day', sa.Integer(), nullable=False),
    sa.Column('maximum_actions_per_day', sa.Integer(), nullable=False),
    sa.Column('require_approval_for_financial_actions', sa.Boolean(), nullable=False),
    sa.Column('require_approval_for_publishing', sa.Boolean(), nullable=False),
    sa.Column('require_approval_for_campaign_creation', sa.Boolean(), nullable=False),
    sa.Column('allowed_platforms', sa.JSON(), nullable=False),
    sa.Column('allowed_actions', sa.JSON(), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_ai_iterations', sa.Integer(), nullable=False),
    sa.Column('max_ai_actions_per_cycle', sa.Integer(), nullable=False),
    sa.Column('max_execution_time', sa.Integer(), nullable=False),
    sa.Column('max_failures_per_cycle', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autonomy_settings_client_id'), 'autonomy_settings', ['client_id'], unique=False)
    op.create_index(op.f('ix_autonomy_settings_organization_id'), 'autonomy_settings', ['organization_id'], unique=False)
    op.create_table('autopilot_runs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('autonomy_mode', sa.String(length=32), nullable=True),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('action_ids', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autopilot_runs_client_id'), 'autopilot_runs', ['client_id'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_organization_id'), 'autopilot_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_autopilot_runs_status'), 'autopilot_runs', ['status'], unique=False)
    op.create_table('client_users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='client_user_role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'user_id', name='uq_client_user')
    )
    op.create_index(op.f('ix_client_users_client_id'), 'client_users', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_users_organization_id'), 'client_users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_client_users_user_id'), 'client_users', ['user_id'], unique=False)
    op.create_table('competitors',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_client_id'), 'competitors', ['client_id'], unique=False)
    op.create_index(op.f('ix_competitors_organization_id'), 'competitors', ['organization_id'], unique=False)
    op.create_table('content_assets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_client_id'), 'content_assets', ['client_id'], unique=False)
    op.create_index(op.f('ix_content_assets_organization_id'), 'content_assets', ['organization_id'], unique=False)
    op.create_table('integrations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_client_id'), 'integrations', ['client_id'], unique=False)
    op.create_index(op.f('ix_integrations_organization_id'), 'integrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_table('leads',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('campaign', sa.String(length=255), nullable=True),
    sa.Column('ad', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('score_explanation', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'qualified', 'interested', 'meeting', 'converted', 'lost', name='lead_status', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_client_id'), 'leads', ['client_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_external_id'), 'leads', ['external_id'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('optimization_rules',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('action_template', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='opt_rule_priority', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_rules_organization_id'), 'optimization_rules', ['organization_id'], unique=False)
    op.create_table('reports',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('export_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_client_id'), 'reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_status', sa.Enum('connected', 'not_connected', 'demo_data', 'sync_error', name='social_connection_status', native_enum=False), nullable=False),
    sa.Column('encrypted_credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_client_id'), 'social_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_organization_id'), 'social_accounts', ['organization_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('main_copy', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=512), nullable=True),
    sa.Column('visual_concept', sa.Text(), nullable=True),
    sa.Column('video_concept', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.Enum('demo', 'live', name='post_data_source', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_client_id'), 'social_posts', ['client_id'], unique=False)
    op.create_index(op.f('ix_social_posts_organization_id'), 'social_posts', ['organization_id'], unique=False)
    op.create_table('strategies',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('current_situation', sa.Text(), nullable=False),
    sa.Column('what_is_happening', sa.Text(), nullable=False),
    sa.Column('key_problems', sa.JSON(), nullable=False),
    sa.Column('opportunities', sa.JSON(), nullable=False),
    sa.Column('strategy_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_client_id'), 'strategies', ['client_id'], unique=False)
    op.create_index(op.f('ix_strategies_organization_id'), 'strategies', ['organization_id'], unique=False)
    op.create_table('action_executions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'executing', 'completed', 'failed', 'cancelled', 'scheduled', name='execution_status', native_enum=False), nullable=False),
    sa.Column('platform_response', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ai_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_executions_action_id'), 'action_executions', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_executions_organization_id'), 'action_executions', ['organization_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('ad_account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('objective', sa.String(length=120), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.Enum('demo', 'live', name='campaign_data_source', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_client_id'), 'campaigns', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_table('content_calendar',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('social_post_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_post_id'], ['social_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_calendar_client_id'), 'content_calendar', ['client_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_organization_id'), 'content_calendar', ['organization_id'], unique=False)
    op.create_table('lead_activities',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_client_id'), 'lead_activities', ['client_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_organization_id'), 'lead_activities', ['organization_id'], unique=False)
    op.create_table('optimization_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='opt_event_priority', native_enum=False), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ai_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['optimization_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_events_organization_id'), 'optimization_events', ['organization_id'], unique=False)
    op.create_table('scheduled_posts',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('social_post_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('publish_result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('action_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ai_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_post_id'], ['social_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_client_id'), 'scheduled_posts', ['client_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_organization_id'), 'scheduled_posts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_scheduled_for'), 'scheduled_posts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_status'), 'scheduled_posts', ['status'], unique=False)
    op.create_table('strategy_actions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=120), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='action_priority', native_enum=False), nullable=False),
    sa.Column('estimated_effort', sa.String(length=64), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=False),
    sa.Column('required_assets', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'completed', name='action_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_actions_client_id'), 'strategy_actions', ['client_id'], unique=False)
    op.create_index(op.f('ix_strategy_actions_organization_id'), 'strategy_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_strategy_actions_status'), 'strategy_actions', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_actions_strategy_id'), 'strategy_actions', ['strategy_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_events_provider_event')
    )
    op.create_index(op.f('ix_webhook_events_client_id'), 'webhook_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_organization_id'), 'webhook_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_table('ad_sets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_sets_campaign_id'), 'ad_sets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_sets_client_id'), 'ad_sets', ['client_id'], unique=False)
    op.create_index(op.f('ix_ad_sets_organization_id'), 'ad_sets', ['organization_id'], unique=False)
    op.create_table('analytics_campaign',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('leads', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cpl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.Enum('demo', 'live', name='analytics_campaign_source', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_campaign_client_id'), 'analytics_campaign', ['client_id'], unique=False)
    op.create_index(op.f('ix_analytics_campaign_date'), 'analytics_campaign', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_campaign_organization_id'), 'analytics_campaign', ['organization_id'], unique=False)
    op.create_table('campaign_health',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('excellent', 'good', 'needs_attention', 'poor', 'critical', name='campaign_health_category', native_enum=False), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_health_campaign_id'), 'campaign_health', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_health_client_id'), 'campaign_health', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaign_health_organization_id'), 'campaign_health', ['organization_id'], unique=False)
    op.create_table('creative_assets',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('provider_asset_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_assets_client_id'), 'creative_assets', ['client_id'], unique=False)
    op.create_index(op.f('ix_creative_assets_organization_id'), 'creative_assets', ['organization_id'], unique=False)
    op.create_table('ads',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('ad_set_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('creative', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_set_id'], ['ad_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_ad_set_id'), 'ads', ['ad_set_id'], unique=False)
    op.create_index(op.f('ix_ads_client_id'), 'ads', ['client_id'], unique=False)
    op.create_index(op.f('ix_ads_organization_id'), 'ads', ['organization_id'], unique=False)
    op.create_table('image_jobs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('creative_asset_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=16), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('queued', 'submitted', 'generating', 'processing', 'downloading', 'uploading', 'running', 'waiting_approval', 'scheduled', 'completed', 'failed', 'retrying', 'cancelled', name='image_job_status', native_enum=False), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_asset_id'], ['creative_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_jobs_idempotency_key'), 'image_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_image_jobs_organization_id'), 'image_jobs', ['organization_id'], unique=False)
    op.create_table('video_jobs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('creative_asset_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('queued', 'submitted', 'generating', 'processing', 'downloading', 'uploading', 'running', 'waiting_approval', 'scheduled', 'completed', 'failed', 'retrying', 'cancelled', name='video_job_status', native_enum=False), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_asset_id'], ['creative_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_jobs_idempotency_key'), 'video_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_video_jobs_organization_id'), 'video_jobs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_jobs_organization_id'), table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_idempotency_key'), table_name='video_jobs')
    op.drop_table('video_jobs')
    op.drop_index(op.f('ix_image_jobs_organization_id'), table_name='image_jobs')
    op.drop_index(op.f('ix_image_jobs_idempotency_key'), table_name='image_jobs')
    op.drop_table('image_jobs')
    op.drop_index(op.f('ix_ads_organization_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_client_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_ad_set_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_creative_assets_organization_id'), table_name='creative_assets')
    op.drop_index(op.f('ix_creative_assets_client_id'), table_name='creative_assets')
    op.drop_table('creative_assets')
    op.drop_index(op.f('ix_campaign_health_organization_id'), table_name='campaign_health')
    op.drop_index(op.f('ix_campaign_health_client_id'), table_name='campaign_health')
    op.drop_index(op.f('ix_campaign_health_campaign_id'), table_name='campaign_health')
    op.drop_table('campaign_health')
    op.drop_index(op.f('ix_analytics_campaign_organization_id'), table_name='analytics_campaign')
    op.drop_index(op.f('ix_analytics_campaign_date'), table_name='analytics_campaign')
    op.drop_index(op.f('ix_analytics_campaign_client_id'), table_name='analytics_campaign')
    op.drop_table('analytics_campaign')
    op.drop_index(op.f('ix_ad_sets_organization_id'), table_name='ad_sets')
    op.drop_index(op.f('ix_ad_sets_client_id'), table_name='ad_sets')
    op.drop_index(op.f('ix_ad_sets_campaign_id'), table_name='ad_sets')
    op.drop_table('ad_sets')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_organization_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_client_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_strategy_actions_strategy_id'), table_name='strategy_actions')
    op.drop_index(op.f('ix_strategy_actions_status'), table_name='strategy_actions')
    op.drop_index(op.f('ix_strategy_actions_organization_id'), table_name='strategy_actions')
    op.drop_index(op.f('ix_strategy_actions_client_id'), table_name='strategy_actions')
    op.drop_table('strategy_actions')
    op.drop_index(op.f('ix_scheduled_posts_status'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_scheduled_for'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_organization_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_client_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index(op.f('ix_optimization_events_organization_id'), table_name='optimization_events')
    op.drop_table('optimization_events')
    op.drop_index(op.f('ix_lead_activities_organization_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_client_id'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_content_calendar_organization_id'), table_name='content_calendar')
    op.drop_index(op.f('ix_content_calendar_client_id'), table_name='content_calendar')
    op.drop_table('content_calendar')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_client_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_action_executions_organization_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_action_id'), table_name='action_executions')
    op.drop_table('action_executions')
    op.drop_index(op.f('ix_strategies_organization_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_client_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_social_posts_organization_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_client_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_social_accounts_organization_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_client_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_client_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_optimization_rules_organization_id'), table_name='optimization_rules')
    op.drop_table('optimization_rules')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_external_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_client_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_organization_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_client_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_content_assets_organization_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_client_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_competitors_organization_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_client_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_client_users_user_id'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_organization_id'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_client_id'), table_name='client_users')
    op.drop_table('client_users')
    op.drop_index(op.f('ix_autopilot_runs_status'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_organization_id'), table_name='autopilot_runs')
    op.drop_index(op.f('ix_autopilot_runs_client_id'), table_name='autopilot_runs')
    op.drop_table('autopilot_runs')
    op.drop_index(op.f('ix_autonomy_settings_organization_id'), table_name='autonomy_settings')
    op.drop_index(op.f('ix_autonomy_settings_client_id'), table_name='autonomy_settings')
    op.drop_table('autonomy_settings')
    op.drop_index(op.f('ix_analytics_daily_organization_id'), table_name='analytics_daily')
    op.drop_index(op.f('ix_analytics_daily_date'), table_name='analytics_daily')
    op.drop_index(op.f('ix_analytics_daily_client_id'), table_name='analytics_daily')
    op.drop_table('analytics_daily')
    op.drop_index(op.f('ix_ai_recommendations_status'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_organization_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_client_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_ai_conversations_organization_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_client_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_ai_actions_status'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_platform'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_organization_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_client_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_action_type'), table_name='ai_actions')
    op.drop_table('ai_actions')
    op.drop_index(op.f('ix_ad_accounts_organization_id'), table_name='ad_accounts')
    op.drop_index(op.f('ix_ad_accounts_client_id'), table_name='ad_accounts')
    op.drop_table('ad_accounts')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_business_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_organization_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_locked_by'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_lease_expires_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
