#!/usr/bin/env python
"""
End-to-end verification for the P2-A creative and campaign engine.

Why this exists alongside the test suite: the tests drive handlers directly so
they stay fast and deterministic. This script instead drives the *deployed*
shape of the system — HTTP requests in one place, the real `Worker` process loop
draining the queue in another — and then reads the generated bytes back out of
object storage through the authenticated API. That is the only way to show the
pipeline works end to end rather than showing that each piece works in isolation.

It refuses to overstate its result. The provider actually in use is reported as
REAL, DEMO or NOT_CONFIGURED, and a run against the demo provider is labelled as
such: it proves storage, retrieval, authorization and the job pipeline, and
proves nothing whatsoever about a real vendor's output.

    # against the local SQLite database
    python scripts/verify_p2a_e2e.py

    # against PostgreSQL
    DATABASE_URL="postgresql+asyncpg://growthos:growthos@127.0.0.1:55433/growthos_p2a" \
      python scripts/verify_p2a_e2e.py

Exit code 0 means every check passed. 1 means a check failed. 2 means the script
could not run.
"""

from __future__ import annotations

import asyncio
import os
import sys
import uuid
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

os.environ.setdefault("DEMO_MODE", "true")
os.environ.setdefault("STORAGE_BACKEND", "local")
os.environ.setdefault("STORAGE_LOCAL_PATH", "./storage_verify_p2a")
# Development defaults to running jobs inline, which would let this script pass
# without a worker ever existing. Forced off so the queue path is what is
# actually verified — the same path production uses.
os.environ.setdefault("INLINE_JOB_EXECUTION", "false")

from httpx import ASGITransport, AsyncClient  # noqa: E402

from app.core.config import get_settings  # noqa: E402
from app.core.security import hash_password  # noqa: E402
from app.db.session import AsyncSessionLocal  # noqa: E402
from app.generation import get_image_provider, get_video_provider  # noqa: E402
from app.main import app  # noqa: E402
from app.models.client import Client  # noqa: E402
from app.models.enums import MemberRole  # noqa: E402
from app.models.organization import Organization, OrganizationMember  # noqa: E402
from app.models.user import User  # noqa: E402
from app.worker import Worker  # noqa: E402

PASSWORD = "Verify-P2A-Passw0rd!"

IMAGE_MAGIC = {
    b"\x89PNG\r\n\x1a\n": "image/png",
    b"\xff\xd8\xff": "image/jpeg",
    b"RIFF": "image/webp",
}


@dataclass
class Report:
    checks: list[tuple[bool, str]] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def check(self, ok: bool, description: str) -> bool:
        self.checks.append((bool(ok), description))
        print(f"  {'PASS' if ok else 'FAIL'}  {description}")
        return bool(ok)

    def note(self, text: str) -> None:
        self.notes.append(text)
        print(f"  note  {text}")

    @property
    def failed(self) -> list[str]:
        return [text for ok, text in self.checks if not ok]


async def make_tenant(label: str, role: MemberRole = MemberRole.owner) -> tuple[str, uuid.UUID]:
    suffix = uuid.uuid4().hex[:8]
    email = f"{label}-{suffix}@verify-p2a.example.com"
    async with AsyncSessionLocal() as db:
        user = User(email=email, hashed_password=hash_password(PASSWORD), full_name="Verifier")
        org = Organization(name=f"Verify {suffix}", slug=f"verify-{suffix}", demo_mode=True)
        db.add_all([user, org])
        await db.flush()
        db.add(OrganizationMember(organization_id=org.id, user_id=user.id, role=role))
        client = Client(
            organization_id=org.id,
            business_name=f"Verify Client {suffix}",
            industry="home_services",
            website="https://example.com",
            description="A local roofing company serving three suburbs.",
            location="Austin, TX",
            products_services="Roof repair, full replacement, storm damage inspection",
            target_audience="Homeowners aged 35-60 who own their property",
            marketing_goals="Book more inspection appointments",
            brand_voice="Direct, reassuring, no hype",
        )
        db.add(client)
        await db.commit()
        return email, client.id


async def login(http: AsyncClient, email: str) -> dict[str, str]:
    resp = await http.post("/api/v1/auth/login", json={"email": email, "password": PASSWORD})
    resp.raise_for_status()
    return {"Authorization": f"Bearer {resp.json()['access_token']}"}


async def drain_queue(*, max_cycles: int = 40) -> int:
    """
    Run the real worker until the queue is empty.

    Uses `app.worker.Worker`, not a bespoke loop, so this exercises the same
    claiming, leasing and retry code that runs in production.
    """
    worker = Worker(batch_size=10, poll_interval=0.0, lease_seconds=120)
    executed = 0
    idle_cycles = 0
    for _ in range(max_cycles):
        count = await worker.run_once()
        executed += count
        if count == 0:
            idle_cycles += 1
            # Two idle cycles in a row: reconcile jobs are scheduled with a delay,
            # so one empty cycle does not prove the queue is finished.
            if idle_cycles >= 2:
                break
            await asyncio.sleep(0.4)
        else:
            idle_cycles = 0
    return executed


async def main() -> int:
    settings = get_settings()
    report = Report()

    image = get_image_provider()
    video = get_video_provider()
    image_kind = provider_kind(image.name, image.configured())
    video_kind = provider_kind(video.name, video.configured())

    print("P2-A end-to-end verification")
    print("=" * 72)
    print(f"  database        {redact_dsn(settings.database_url)}")
    print(f"  storage         {settings.storage_backend}")
    print(f"  image provider  {image.name} -> {image_kind}")
    print(f"  video provider  {video.name} -> {video_kind}")
    print()

    if image_kind == "REAL":
        report.note("A real image provider is configured; generated bytes come from the vendor.")
    elif image_kind == "DEMO":
        report.note(
            "IMAGE_PROVIDER=demo. This run verifies the pipeline, storage and "
            "authorization only. It does NOT verify a real vendor's output."
        )
    else:
        report.note("No image provider configured; images must report NOT_CONFIGURED.")
    if video_kind == "NOT_CONFIGURED":
        report.note("No video provider configured; videos must report NOT_CONFIGURED.")

    owner_email, client_id = await make_tenant("owner")
    other_email, _ = await make_tenant("other")

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test", timeout=120.0) as http:
        owner = await login(http, owner_email)
        other = await login(http, other_email)

        # ------------------------------------------------------------------
        print("\n1. Generator options")
        options = await http.get("/api/v1/campaign-generation/options", headers=owner)
        report.check(options.status_code == 200, "options are readable")
        body = options.json()
        report.check(len(body["platforms"]) >= 4, "platforms are configured, not hard-coded")
        report.check(
            all(not p["publishing_supported"] for p in body["platforms"]),
            "no platform claims publishing support",
        )
        report.check(
            body["media"]["image_configured"] == image.configured(),
            "reported image provider state matches the backend",
        )

        # ------------------------------------------------------------------
        print("\n2. Accepted asynchronously")
        started = await http.post(
            "/api/v1/campaign-generation/generate",
            headers=owner,
            json={
                "client_id": str(client_id),
                "platform": "meta",
                "objective": "lead_generation",
                "offer": "Free storm damage inspection",
                "daily_budget": "120.00",
                "currency": "USD",
                "concept_quantity": 3,
                "image_quantity": 3,
                "video_quantity": 1,
                "variation_quantity": 2,
            },
        )
        report.check(started.status_code == 202, f"generate returns 202 (got {started.status_code})")
        if started.status_code != 202:
            print(started.text)
            return finish(report)
        run = started.json()
        report.check(run["status"] in {"QUEUED", "GENERATING"}, "run starts unfinished")
        report.check(bool(run["stages"]), "stages are published for the UI to poll")

        # ------------------------------------------------------------------
        print("\n3. Background worker drains the queue")
        executed = await drain_queue()
        report.check(executed > 0, f"worker executed jobs out of band ({executed} job runs)")

        current = await http.get(f"/api/v1/campaign-generation/runs/{run['id']}", headers=owner)
        run = current.json()
        report.check(
            run["status"] == "READY_FOR_REVIEW",
            f"run reached READY_FOR_REVIEW (got {run['status']})",
        )
        campaign_id = run["campaign_id"]
        report.check(bool(campaign_id), "a campaign was created")
        if not campaign_id:
            return finish(report)

        # ------------------------------------------------------------------
        print("\n4. Reviewable package")
        package = (
            await http.get(
                f"/api/v1/campaign-generation/campaigns/{campaign_id}/package", headers=owner
            )
        ).json()
        report.check(package["strategy"] is not None, "strategy is present")
        report.check(
            bool(package["strategy"]["current_situation"]) and bool(package["strategy"]["problem"]),
            "strategy sections are populated",
        )
        report.check(package["brief"] is not None, "brief is present")
        report.check(len(package["concepts"]) == 3, "three concepts were produced")
        angles = {c["angle"] for c in package["concepts"]}
        report.check(len(angles) == 3, "the concepts are distinct hypotheses, not rewordings")
        report.check(
            all(c["image_prompt"] and len(c["image_prompt"]) > 60 for c in package["concepts"]),
            "each concept carries a specific image prompt",
        )
        report.check(bool(package["ad_sets"]), "ad sets were built")
        report.check(bool(package["ads"]), "ads were built")
        variations = [v for c in package["concepts"] for v in c["variations"]]
        report.check(len(variations) >= 2, f"variations were produced ({len(variations)})")
        report.check(
            all(v["axis"] and v["hypothesis"] for v in variations),
            "every variation names the axis it changes and its hypothesis",
        )
        report.check(
            "no advertising money has been spent" in package["publishing_note"],
            "the package states that nothing was published",
        )

        # ------------------------------------------------------------------
        print("\n5. Generated media")
        assets = [a for c in package["concepts"] for a in c["assets"]]
        images = [a for a in assets if a["kind"] == "image"]
        videos = [a for a in assets if a["kind"] == "video"]
        stages = {s["key"]: s for s in package["run"]["stages"]}

        if image.configured():
            report.check(len(images) == 3, f"three image slots exist ({len(images)})")
            stored = [a for a in images if a["status"] == "COMPLETED"]
            report.check(bool(stored), f"images completed ({len(stored)}/{len(images)})")
            for asset in stored:
                report.check(bool(asset["url"]), "a completed image exposes an authenticated url")
                fetched = await http.get(asset["url"], headers=owner)
                report.check(fetched.status_code == 200, "stored bytes are retrievable")
                magic = next(
                    (mime for prefix, mime in IMAGE_MAGIC.items() if fetched.content.startswith(prefix)),
                    None,
                )
                report.check(magic is not None, f"stored object is a real image ({magic})")
                report.check(len(fetched.content) > 100, f"file has content ({len(fetched.content)} bytes)")
                report.check(
                    asset["demo"] is (image_kind == "DEMO"),
                    "the asset is labelled DEMO if and only if it came from the demo provider",
                )

                download = await http.get(f"{asset['url']}?download=true", headers=owner)
                report.check(
                    "attachment" in download.headers.get("content-disposition", ""),
                    "authorized download is served as an attachment",
                )

                cross = await http.get(asset["url"], headers=other)
                report.check(
                    cross.status_code == 404,
                    "another organization cannot download the asset (404, not 403)",
                )
        else:
            # No provider means no job and no asset row — there is nothing to
            # record. The stage is what carries the explanation, so assert there
            # rather than over an empty list, which would pass vacuously.
            report.check(
                stages.get("images", {}).get("status") == "NOT_CONFIGURED",
                f"the image stage reports NOT_CONFIGURED (got {stages.get('images', {}).get('status')})",
            )
            report.check(not images, "no image asset was invented for an unconfigured provider")

        if video.configured():
            report.check(
                all(v["status"] != "COMPLETED" or v["url"] for v in videos),
                "a completed video has stored bytes",
            )
        else:
            report.check(
                stages.get("videos", {}).get("status") == "NOT_CONFIGURED",
                f"the video stage reports NOT_CONFIGURED (got {stages.get('videos', {}).get('status')})",
            )
            report.check(not videos, "no MP4 was fabricated for an unconfigured provider")

        # ------------------------------------------------------------------
        print("\n6. Tenant isolation")
        for label, response in {
            "run": await http.get(f"/api/v1/campaign-generation/runs/{run['id']}", headers=other),
            "package": await http.get(
                f"/api/v1/campaign-generation/campaigns/{campaign_id}/package", headers=other
            ),
            "approve": await http.post(
                f"/api/v1/campaign-generation/campaigns/{campaign_id}/approve",
                headers=other,
                json={},
            ),
        }.items():
            report.check(response.status_code == 404, f"another organization cannot reach the {label}")

        # ------------------------------------------------------------------
        print("\n7. Approval")
        approved = await http.post(
            f"/api/v1/campaign-generation/campaigns/{campaign_id}/approve",
            headers=owner,
            json={"comment": "Verified end to end."},
        )
        report.check(approved.status_code == 200, "the owner can approve")
        approval = approved.json()["approval"]
        report.check(
            approval["review_status"] == "READY_TO_PUBLISH",
            f"approval moves to READY_TO_PUBLISH (got {approval['review_status']})",
        )
        report.check(bool(approval["approved_by"]) and bool(approval["approved_at"]),
                     "approval records who and when")
        report.check(
            approval["external_id"] is None,
            "no external campaign id exists — nothing was published",
        )

        repeat = await http.post(
            f"/api/v1/campaign-generation/campaigns/{campaign_id}/approve",
            headers=owner,
            json={},
        )
        report.check(repeat.status_code == 409, "approving twice is a conflict, not a silent no-op")

        # ------------------------------------------------------------------
        print("\n8. Library")
        library = await http.get(
            f"/api/v1/creative/assets?campaign_id={campaign_id}", headers=owner
        )
        report.check(library.status_code == 200, "the library lists the campaign's assets")
        rows = library.json()
        report.check(
            all(r["client_id"] == str(client_id) for r in rows),
            "every listed asset belongs to this client",
        )
        empty = await http.get(f"/api/v1/creative/assets?campaign_id={campaign_id}", headers=other)
        report.check(empty.json() == [], "the other organization sees none of them")

    return finish(report)


def provider_kind(name: str, configured: bool) -> str:
    if not configured:
        return "NOT_CONFIGURED"
    return "DEMO" if name in {"demo", "mock", "stub"} else "REAL"


def redact_dsn(url: str) -> str:
    if "@" not in url:
        return url
    scheme, rest = url.split("://", 1)
    return f"{scheme}://***@{rest.split('@', 1)[1]}"


def finish(report: Report) -> int:
    total = len(report.checks)
    failed = report.failed
    print("\n" + "=" * 72)
    print(f"{total - len(failed)}/{total} checks passed")
    for text in failed:
        print(f"  FAILED: {text}")
    print()
    for note in report.notes:
        print(f"  {note}")
    return 1 if failed else 0


if __name__ == "__main__":
    try:
        sys.exit(asyncio.run(main()))
    except KeyboardInterrupt:
        sys.exit(2)
